services:
  nginx:
    container_name: ${CONTAINER_NAME}-nginx
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    restart: unless-stopped
    env_file: .env
    ports:
      - "80:80"
      - "443:443"
    healthcheck:
      test: [ "CMD", "nginx", "-t" ]
      interval: 10s
      timeout: 5s
      retries: 3
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - wordpress:/var/www/html
    networks:
      - internal

  database:
    image: mysql:8.0
    container_name: ${CONTAINER_NAME}-database
    restart: unless-stopped
    env_file: .env
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - internal
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$DATABASE_ROOT_PASSWORD" ]
      timeout: 20s
      retries: 10

  wordpress:
    image: wordpress:6.5.2-fpm-alpine
    container_name: ${CONTAINER_NAME}-wordpress
    depends_on:
      - database
    restart: unless-stopped
    env_file: .env
    environment:
      WORDPRESS_DB_HOST: database:3306
      WORDPRESS_DB_NAME: ${DATABASE_NAME}
      WORDPRESS_DB_USER: ${DATABASE_USER}
      WORDPRESS_DB_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - wordpress:/var/www/html
      - ./wp-content:/var/www/html/wp-content:rw
    networks:
      - internal
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 5

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: ${CONTAINER_NAME}-phpmyadmin
    env_file: .env
    environment:
      PMA_HOST: database
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
    ports:
      - "8081:80"
    networks:
      - internal

  cloudflared:
    container_name: ${CONTAINER_NAME}-cloudflared
    image: cloudflare/cloudflared:latest
    restart: always
    command: [ "tunnel", "--config", "/etc/cloudflared/config.yml", "--autoupdate-freq", "24h", "run" ]
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}
    depends_on:
      nginx:
        condition: service_healthy
    volumes:
      - ./cloudflared:/etc/cloudflared:ro
    networks:
      - internal

volumes:
  db_data:
  wordpress:


networks:
  internal:
    driver: bridge
